### ISSUE TITLE
More explicit types in relations

### ISSUE THREAD

**Issue by Vrixyz** [TeXitoi/osmpbfreader-rs#16]
Hello,

I notice data structure for tags in at the “simplest” state right now, but some data values in osm is pretty established : I’m thinking about relation types : https://wiki.openstreetmap.org/wiki/Types_of_relation.

Would it be consistent to reflect that in this source code ? Or is it too specific and up to a higher level project ?

**Comment by TeXitoi** [comment]
Sorry forgot to respond.

osmpbfreader is agnostic to tag interpretation, thus including knowledge of the usage of the data is out of scope.

What do you want to do?

**Comment by Vrixyz** [comment]
I see, I didn't think about being "tag agnostic", that clears my questions: I wanted to know if such contributions would be welcome. I guess that would be the purpose of another library, or example files. But I'll pass.

Thanks for the answer :)

**Comment by TeXitoi** [comment]
There is a few useful utils around osmpbfreader as https://crates.io/crates/osm_boundaries_utils
