### ISSUE TITLE
Missing suppport for contours pbf node

### ISSUE THREAD

**Issue by Gansgar** [TeXitoi/osmpbfreader-rs#23]

**Comment by TeXitoi** [comment]
What is that? can you elaborate?

**Comment by Gansgar** [comment]
I don't have the tools on hand to debug the pbf file, the library only returns `InvalidData` objects on this pbf file:
https://drive.google.com/file/d/1jYnabiJLCFR-RNAa0tzyuG6f067UzDMB/view?usp=sharing

**Comment by Gansgar** [comment]
I think its this proto file:
https://github.com/mapbox/vector-tile-spec/blob/master/1.0.0/vector_tile.proto

**Comment by TeXitoi** [comment]
This package is to read OSM PBF files: https://wiki.openstreetmap.org/wiki/PBF_Format

You try to read tile files with it, thus it doesn't work.

**Comment by Gansgar** [comment]
Ah thanks. Sorry for that
