### ISSUE TITLE
Removing flat_map dependency?

### ISSUE THREAD

**Issue by GuillaumeGomez** [TeXitoi/osmpbfreader-rs#27]
Following my PR yesterday, I worked in parallel on https://github.com/toffaletti/flat_map/pull/11 . However, this crate seems more or less dead. Should I fork it and release it under the same flat_map2 or something equivalent or should we just remove this dependency and merge whatever part of the code we might be interested in?

**Comment by TeXitoi** [comment]
We might switch to https://crates.io/crates/map_vec also
