### ISSUE TITLE
Use MIT licensed .proto files

### ISSUE THREAD

**Issue by fsasm** [TeXitoi/osmpbfreader-rs#32]
The .proto files in the original [OSM-Binary](https://github.com/openstreetmap/OSM-binary) repository were relicensed to MIT ([commit](https://github.com/openstreetmap/OSM-binary/commit/5a4c8c11564104afca14b787ef14131053977b5b)) back in July 2019. The corresponding files in this repository are still licensed under LGPLv3. I suggest to import the files with the new license and change the License section in README.md to mention the MIT license.

**Comment by TeXitoi** [comment]
Good idea, fans there is dome warnings when compiling the generated file.

I can't do that this week as I'm in holidays but feel créé to oinh me within 2 weeks if I didn't give you any news here.

**Comment by TeXitoi** [comment]
Sorry, auto correction on mobile, hope you'll be able to understand.

**Comment by TeXitoi** [comment]
Done in #33
