### ISSUE TITLE
Do not pass the world platnet pbf

### ISSUE THREAD

**Issue by lygstate** [TeXitoi/osmpbfreader-rs#9]

**Comment by TeXitoi** [comment]
Can you give more details please. One time I've read a planet with this library. A link to the file, a small main showing the problem, and a trace of the program crashing would help reproduce.

Be aware that, if you use `get_objs_and_deps`, you are limited to your memory as every filtered objects are loaded.

**Comment by lygstate** [comment]
see that

**Comment by lygstate** [comment]
I am using count with deps may that be the problem？

**Comment by TeXitoi** [comment]
Yes, your program must be OOM killed.

**Comment by lygstate** [comment]
would count works

**Comment by TeXitoi** [comment]
yes
